version: 2.0
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Print Environment Variables
          command: env

      - run:
          name: My Environment 
          command: |
             echo "Environment : $CIRCLE_PROJECT_REPONAME"
